server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
        #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://:3307/hotel?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
#    username: Hotel
#    password: Hotel
  
  mvc:         #引入mvn配置
    view:
      prefix: /WEB-INF/   # /默认代表根目录 src/main/webapp
      suffix: .jsp      #配制后缀

#mybatisPlus配制
mybatis-plus:
    #别名包定义 
  type-aliases-package: com.hotel.pojo
    #引入映射文件
  mapper-locations: classpath:/mybatis/mappers/*.xml
    #开启驼峰映射 实现了字段与属性映射 自动去除"_" 并且之后的首字母大写
  configuration:
    map-underscore-to-camel-case: true

#日志输出
logging:
  level:
    com.hotel.mapper: debug 
    
#dubbo提供者配置 
dubbo:
  scan:
    basePackages: com.hotel
  application:
    name: provider-manage
  registry:
    address: zookeeper://192.168.198.130:2181?backup=192.168.198.130:2182,192.168.198.130:2183
  protocol:
    name: dubbo  #dubbo节点保存的名称
    port: 20890  #dubbo RPC调用的端口信息

  

  
  
