server:
  port: 8082    
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

#dubbo消费者配置
dubbo:
  scan:
    basePackages: com.hotel
  application:
    name: consumer-endWeb
  registry:
    address: zookeeper://49.233.79.16:2181?backup=49.233.79.16:2182,49.233.79.16:2183