server:
  port: 8080    
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

#dubbo消费者配置
dubbo:
  scan:
    basePackages: com.hotel
  application:
    name: consumer-web
  registry:
    address: zookeeper://192.168.198.130:2181?backup=192.168.198.130:2182,192.168.198.130:2183